// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VulnerableAPI.Data;

#nullable disable

namespace VulnerableAPI.Migrations
{
    [DbContext(typeof(VulnerableDbContext))]
    partial class VulnerableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VulnerableAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2170),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 1299.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2173),
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 29.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2175),
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 89.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2176),
                            Description = "4K Monitor 27 inch",
                            Name = "Monitor",
                            Price = 399.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2177),
                            Description = "USB-C cable 2m",
                            Name = "USB Cable",
                            Price = 12.99m,
                            Stock = 500
                        });
                });

            modelBuilder.Entity("VulnerableAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin Street",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2021),
                            CreditCardNumber = "4532-1234-5678-9010",
                            Email = "admin@vulnerable.api",
                            FullName = "System Administrator",
                            IsAdmin = true,
                            Password = "admin123",
                            PhoneNumber = "555-0001",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 User Lane",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2022),
                            CreditCardNumber = "4532-9876-5432-1098",
                            Email = "john@vulnerable.api",
                            FullName = "John Doe",
                            IsAdmin = false,
                            Password = "12345",
                            PhoneNumber = "555-0002",
                            Username = "john"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Customer Blvd",
                            CreatedAt = new DateTime(2026, 2, 15, 16, 55, 13, 923, DateTimeKind.Utc).AddTicks(2024),
                            CreditCardNumber = "4532-1111-2222-3333",
                            Email = "jane@vulnerable.api",
                            FullName = "Jane Smith",
                            IsAdmin = false,
                            Password = "password",
                            PhoneNumber = "555-0003",
                            Username = "jane"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
