sonar.projectKey=.NET-Vulnerable-API
sonar.projectVersion=3.0
sonar.working.directory=C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API
sonar.pullrequest.cache.basepath=C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API
sonar.sources=\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.vs\\VulnerableAPI\\config\\applicationhost.config",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.vs\\VulnerableAPI\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.vs\\VulnerableAPI\\v18\\DocumentLayout.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\docker-compose.yml",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\start.sh"

4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.projectKey=.NET-Vulnerable-API:4ECD66E5-E215-4B7D-BF7B-FB601118A58F
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.projectName=VulnerableAPI
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.projectBaseDir=C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.sourceEncoding=utf-8
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.tests=
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.sources=\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Auth\\DepartmentBasedDocumentRequirementHandler .cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Auth\\DocumentRequirement.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Auth\\DocumentRequirementHandler.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\AuthController.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\AuthControllerV2.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\DocumentsController.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\ProductController.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\UserController.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Controllers\\UtilityController.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Data\\AppIdentityDbContext.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Data\\VulnerableDbContext.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\20260215165514_First.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\20260215165514_First.Designer.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\20260226071024_Second.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\20260226071024_Second.Designer.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\Identity\\20260220125219_App_Identity_Context.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\Identity\\20260220125219_App_Identity_Context.Designer.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\Identity\\AppIdentityDbContextModelSnapshot.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Migrations\\VulnerableDbContextModelSnapshot.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\AppRole.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\AppUser.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\AuthModels.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\Document.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\DocumentDto.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\Product.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\TokenResponse.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Models\\User.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Program.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\VulnerableAPI.GlobalUsings.g.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\VulnerableAPI.AssemblyInfo.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\VulnerableAPI.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\appsettings.Development.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\appsettings.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\.dockerignore",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Dockerfile",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\AUTH_README_TR.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\AUTH_ZAFIYETLER_TR.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\JWT_ATTACK_GUIDE.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\PRODUCT_README_TR.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\PRODUCT_ZAFIYETLER_TR.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Docs\\UtilityController.README.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\README.md",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\VulnerableAPI.http",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\Properties\\launchSettings.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\project.assets.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\VulnerableAPI.csproj.nuget.dgspec.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\bin\\Debug\\net8.0\\VulnerableAPI.deps.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\bin\\Debug\\net8.0\\VulnerableAPI.runtimeconfig.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\bin\\Debug\\net8.0\\VulnerableAPI.staticwebassets.endpoints.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\VulnerableAPI.sourcelink.json",\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\VulnerableAPI\\obj\\Debug\\net8.0\\EndpointInfo\\VulnerableAPI.json"

4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.sonarqube\\out\\0"
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.sonarqube\\out\\0\\Issues.json"
4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.cs.scanner.telemetry=\
"C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.sonarqube\\out\\0\\Telemetry.json"

4ECD66E5-E215-4B7D-BF7B-FB601118A58F.sonar.working.directory=C:\\Users\\Administrator\\Desktop\\Apps\\.NET-Vulnerable-API\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.exclusions=**/Program.cs
sonar.visualstudio.enable=false

sonar.modules=4ECD66E5-E215-4B7D-BF7B-FB601118A58F

